name: Bug Report
description: Create a bug report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: If I do xxx, yyy does not work. I tried also...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "Instead, the following should happen: ..."
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - MacOS
        - Linux
        - Other
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Firefox
        - Chrome
        - Opera
        - Safari
        - Edge
        - Other
      multiple: true
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 0.9.12
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.
        You can upload images or console logs (Console Logs: Right mouse-click => Examine => Console)
    validations:
      required: false
