blank_issues_enabled: true
contact_links:
  - name: Ask a Question / Discussion
    url: https://github.com/2Abendsegler/GClh/discussions/new
    about: You are not sure whether your request is a bug report or a feature request or you have a question about how something works? Then the discussion forum is the right one!
