name: Feature Request
description: Here you can ask for a new function
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to share your ideas.
  - type: textarea
    id: idea
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots or workarounds about the feature request here.
    validations:
      required: false
